export const notificationSound = "data:audio/mpeg;base64,//uQxAAAAAAAAAAAAEluZm8AAAAPAAAABAAAACwAAAAAAABew50AAABAAABXsOQAABAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA//uQxAAAAAAAABAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAA";
// Note: The above is a dummy placeholder. Ideally use a real short beep base64. 
// Since I cannot generate a real mp3 binary here easily, I will rely on a simple beep url or just the logic. 
// Actually, I can use a standard URL if the user is online, but let's try to be self-contained.
// For the sake of this task, I will use a publicly available reliable URL in the code instead of a large base64 string.

export const notificationSoundUrl = "https://assets.mixkit.co/active_storage/sfx/2869/2869-preview.mp3"; 
